### ISSUE TITLE
10 Bold logo not updated in Perth, still shows 10HD logo

### ISSUE THREAD

**Issue by louis6321** [markcs/xml_tv#36] opened 2020-11-14 12:23 UTC
10 Bold now occupies channels 1 and 12 in Perth.
Personally I disable channel 1 and just use 12. In any case, the logo for both is still showing 10HD.

This is not a cache issue on my end; I can see it's like that in the xml source file:

http://img-store-prod.switch.tv/images/a2c71d35-21c2-4d70-a585-bdba26f3d41e/getimage.php%3FsiteID%3D288%26group%3DSTILL%26tag%3DIMAGE%26videoID%3D1466548

**Comment by markcs** [comment] 2020-11-14 22:42
I'm working on a fix for this. 

The YourTV website has 10 Bold as channel 1 in Melbourne, but it is on Channel 12 only.  The Channel 1 broadcast is actually  10 HD.

Are you sure 10 Bold is also broadcast on both channel 1 and 12 in Perth or just 12?

**Comment by louis6321** [comment] 2020-11-15 02:56
Sorry, you are correct. 1 is indeed 10HD. Not sure why I wrote that last night.

So yes, 10 Bold is only on 12.

**Comment by markcs** [comment] 2020-11-16 00:20
The 10Bold issue should be fixable by the update I just pushed to branch markcs-testing. 

The issue for some regions is that the YourTV website does not give the correct number for Bold - normally it gives channel 1 instead of 10.  This creates an issue with the icons.

You need to map the channel that is given by YourTV to the correct channel.   If you run this locally, you can test this now by looking at the config files and the new option that was added.  Otherwise wait a few days until this is updated on xmltv.net

**Comment by markcs** [comment] 2020-12-01 11:12
This should be fixed in the latest update.  Please refresh your guide or remap channels if required.  Comment here if the issue is still seen

**Closed by markcs** 2020-12-01 11:12 UTC
