### ISSUE TITLE
Icons Missing

### ISSUE THREAD

**Issue by trentten** [markcs/xml_tv#34] opened 2020-10-06 15:38 UTC
First up, I'd love to send all my love and appreciation for this project. I've been using it from the beginning after Plex switched data providers and it's been perfect!

I've noticed some issues lately with occasional icons not showing up in the guide (usually the HD channels). Currently I have channel 15, 30 and 74 missing. In addition channel 12 is also showing as 10HD but should be 10Bold.

Am I the only one having this issue? If so, is there something I can do to fix it?
Otherwise is this an XML issue that can be resolved or a yourtv problem that is out of our control?

**Comment by trentten** [comment] 2020-10-07 04:17
On further investigation I found that the icons do show up on all my other devices it appears to just be the web-interface that have missing icons. Not as problematic.

Channel 12 showing as 10HD instead of 10BOLD is still an issue on all devices.

**Comment by markcs** [comment] 2020-11-16 00:19
The 10Bold issue should be fixable by the update I just pushed to branch markcs-testing. 

The issue for some regions is that the YourTV website does not give the correct number for Bold - normally channel 1 instead of 10.  This creates an issue with the icons.

You need to map the channel that is given by YourTV to the correct channel.   If you run this locally, you can test this now by looking at the config files and the new option that was added.  Otherwise wait a few days until this is updated on xmltv.net

**Comment by trentten** [comment] 2020-11-16 13:25
No worries Mark. Thanks for the update :)

**Comment by markcs** [comment] 2020-12-01 11:11
This should be fixed in the latest update.  Please refresh your guide or remap channels if required.  Comment here if the issue is still seen

**Closed by markcs** 2020-12-01 11:11 UTC
