### ISSUE TITLE
Empty Guide When HD Channels Only Selected

### ISSUE THREAD

**Issue by wesf99** [markcs/xml_tv#37] opened 2020-11-21 01:50 UTC
Thank you for providing a great service. I have been using ICE TV EPG on my Plex Server until I recently found your guide. 

From the Plex Live TV & DVR Guide view, when I select HD Channels Only, the Guide is empty.  While this is a minor issue, I tend to mostly watch HD channels and it would be great  if I could get it to work. 

![Capture 2](https://user-images.githubusercontent.com/55278725/99864523-ce5f0580-2bde-11eb-9aa1-9c08bca6dc40.PNG)
![Capture 1](https://user-images.githubusercontent.com/55278725/99864526-d0c15f80-2bde-11eb-976f-154713a60541.PNG)

I am in Perth and I use the Perth xml.

**Comment by markcs** [comment] 2020-11-21 02:09
This issue should hopefully be fixed in the next release.

Can you please confirm the HD channel numbers in Perth?

**Comment by wesf99** [comment] 2020-11-21 03:24
Very speedy response. Thanks you. 

The Perth HD channels are are:

  1 10 HD AVC HD
15 10 HD AVC HD
20 ABC HD AVC HD
30 SBS ONE HD AVC HD
31 SBS VICELAND HD AVC HD
32 SBS World Movie AVC HD
70 7HD Perth AVC HD
74 7mateHD Perth AVC HD
90 9HD Perth AVC HD
95 9GemHD Perth AVC HD

**Comment by markcs** [comment] 2020-11-22 07:51
I've made the changes to the code in branch markcs-testing.  You will just need to wait until xmltv.net is updated with the script and the updated script is tested there.  This may take a few more days.

**Comment by markcs** [comment] 2020-12-01 11:12
This should be fixed in the latest update.  Please refresh your guide or remap channels if required.  Comment here if the issue is still seen

**Closed by markcs** 2020-12-01 11:12 UTC

**Comment by wesf99** [comment] 2020-12-01 23:10
Thanks Mark. All fixed
